# -*- coding: utf-8 -*-
# @Time    : 2023/5/9 18:03
# @Author  : PFinal南丞 <lampxiezi@163.com
# @File    : replace_tool.py
# @Software: PyCharm

item = [
    "webgl-fingerprint-defender-alert",
    "userAgent:",
    "1234567812345678",
    "not a function",
    "resolve",
    "BOOLEAN",
    "webkitAudioContext",
    "htHdaQwhjBhHGZ7W",
    "Bookman Old Style",
    "clamp",
    "(Windows NT 10.0; Win64; x64",
    "Offset: ",
    "outerHTML",
    "stream",
    "gesture",
    "zSHLaXwGjtQIY37Wez",
    "U",
    "innerHTML",
    "bingpreview",
    "en-US,en",
    " (constructed)",
    "s",
    "adblock2345",
    "TrackEvent",
    "_",
    "setItem",
    "idf",
    "hSHQaIEGREhHYp7A",
    "\\",
    "edit",
    "initialized",
    "i init ok",
    "ZERO",
    "pos",
    "canvas-fingerprint-defender-alert",
    "tag",
    "url",
    "flush",
    "rv:11.0",
    "_nDataBytes",
    "undefined",
    "WINNDOWS",
    "-9999px",
    "[header:",
    "onmouseout",
    "outerWidth",
    "Arial Rounded MT Bold",
    "isEven",
    "02",
    "~/",
    "Calibri",
    "splice",
    "mozilla",
    "compareTo",
    "xdid",
    "Wingdings 3",
    "__creator",
    "VConsole",
    "unload",
    "jyru",
    "3.8.6",
    "Century Schoolbook",
    "IOS",
    "src",
    "DeviceMotionEvent",
    "hexCurrent",
    "audiocontext-fingerprint-defender",
    "^^",
    "showModalDialog",
    "toHexDOM",
    "attachShader",
    "fromInt",
    "webkitRequestFileSystem",
    "appendASN1Object",
    "oid",
    "tIndex",
    "sigBytes",
    "N",
    "usage",
    "FIqG",
    "FfhJ",
    "index",
    "text-align-last",
    "Pkcs7",
    "REAL",
    "*",
    " hover",
    "str",
    "app_name",
    "Helvetica",
    "monospace",
    "BLACKBERRY",
    "getParameter",
    "DERAbstractTime",
    "x509",
    "reason",
    "Object.keys called on non-object",
    "lineHeight",
    "usageDetails",
    " elem)",
    "blackberry",
    "multiplyTo",
    "rShiftTo",
    "posEnd",
    "zVzDIoO7jOhDYy",
    "Shockwave Flash",
    "getinfo",
    "zSHlknEgRLQIGZ7eeNUA",
    "ONE",
    "BADA",
    "__BROWSERTOOLS_DOMEXPLORER_ADDED",
    "setByASN1ObjectArray",
    "wm",
    "doPublic",
    "mac",
    "browserVersion2",
    "defineProperty",
    "setPublicKey",
    "host",
    "linkProgram",
    "cookieEnabled",
    "})",
    "00000000",
    "MS Gothic",
    "F1",
    "SEQUENCE",
    "ua",
    "callee",
    "A",
    "DERUTCTime",
    "data",
    "pushNotification",
    "zVzcaQELjCQqY37bMQUo",
    "intro",
    "spider",
    "vDHC",
    "=; domain=",
    "malformed oid string: ",
    "_x64Fmix",
    "dlen",
    "Verdana",
    "BlockCipherMode",
    "D",
    "_minBufferSize",
    "normal",
    "_DEC_XFORM_MODE",
    "or",
    "Unrecognized time: ",
    "_x64Xor",
    "Array.prototype.indexOf() - can't convert `",
    "a0",
    "h",
    "multiply",
    "application/asx",
    "constructor",
    "timer",
    "setValueHex",
    "DERSequence",
    "V",
    "detectSwitch",
    "firefox",
    "font-fingerprint-defender",
    "Opera",
    "isWebkit",
    "divideAndRemainder",
    "getPrivateBaseKeyB64",
    "isIE",
    "Arial Narrow",
    "_handled",
    "alphabetic",
    "webos",
    "lzbH",
    "http://fp.fraudmetrix.cn",
    "name",
    "ARRAY_BUFFER",
    "_selenium",
    "localStorage",
    "(){[nativecode]}",
    "can't find _fmOpt",
    "Ijcz",
    "  ",
    "webdriver",
    "millerRabin",
    "mozBattery",
    "enumerateDevices",
    " UTC",
    "4enw49pim03",
    "Imnb",
    "Arial Hebrew",
    "charset",
    "<br/>(encapsulates)",
    "Consolas",
    "check",
    "$super",
    "CSS",
    "zSHLIDELjIhriK7AeLUeJqfN",
    "bot",
    "yrHe",
    "ub",
    "Courier New",
    "width",
    "Segoe Script",
    "InstallTrigger",
    "offsetHeight",
    "isUC",
    "mp",
    "h77umrlknir",
    "onload",
    "; expires=",
    "div",
    "setLocalDescription",
    "] expected ",
    "ExecQuery",
    "zPHvawEejqPqY371eQUeJE",
    "drShiftTo",
    "R",
    "reverse",
    "charCodeAt",
    "[object SafariRemoteNotification]",
    "Webkit",
    "BufferedBlockAlgorithm",
    "Latin1",
    "ios",
    "MSPointerEvent",
    "numberOfOutputs",
    "https://fp.tongdun.net",
    "<br/>(constructed)",
    "className",
    "W",
    "FV",
    "uniformOffset",
    "isFunction",
    "q",
    "zIHlanwhRIr9Y3pYMQ",
    "?",
    "hash128",
    "zVzDIoxXjuPSGM7FePU5",
    "EOC",
    "&sdkVersion=",
    "appName",
    "typeName",
    "CbGz",
    "String",
    "screenTop",
    "firstChild",
    "hT",
    "/fp/detect.json",
    "ceil",
    "text",
    "Math",
    "VisibleString",
    "partner",
    "mediaDevices",
    "x",
    "eruda",
    "value hex must be even length: n=",
    "slice",
    "w3",
    "and",
    "Wingdings",
    "false",
    "h1zjawwrtOhqYy71MQ",
    "squareTo",
    "getOwnPropertyDescriptors",
    "Constructor",
    "languages",
    "requestPermission",
    "print",
    "fmTest",
    "UC",
    "ABCDEFGHJIKLMNOQPRSTUVWXYZ",
    "WEBOS",
    "netscape",
    "writeln",
    "createElement",
    "extend failed, please check that ",
    " (undefined)",
    "sdkVersion",
    "dischargingTime",
    "l",
    "bitCount",
    "level",
    "sub",
    "Andale Mono",
    "tdfp",
    "createProgram",
    "android",
    "cookie",
    "getAttribLocation",
    "UNSIGNED_BYTE",
    "#f60",
    "16",
    "Cipher",
    "hasContent",
    "isOpera",
    "_ks",
    "Z",
    "imgLoaded",
    "s38huiupo1g",
    "Console",
    "fpHost",
    "fillText",
    "consoleCheck",
    "DERObjectIdentifier oidName undefined: ",
    "zding_",
    "Edg/",
    "object",
    "UTC",
    "O",
    "webkitRTCPeerConnection",
    "tao",
    "zbHpIXEhRthLGZ7AoNUeb6xgh1zwIXEGjlhFG3",
    "kdf",
    "zPHpanwXjOPFHP7aoQUiJgxmi10wkExeRLPSY371ey",
    "ltx71",
    "Malformed UTF-8 data",
    "&lt;",
    "_x64LeftShift",
    "rgba(102, 204, 0, 0.7)",
    "canSetSearchEngine",
    "phantomjs",
    "iePrivacy",
    "Book Antiqua",
    "explicit",
    "z1zjINELjGhLGP7A",
    "&errorMsg=",
    "ct",
    "body",
    "…",
    "onerror",
    "getSeconds",
    "testBit",
    "Trebuchet MS",
    "CrOS",
    "xor",
    "__IE_DEVTOOLBAR_CONSOLE_COMMAND_LINE",
    "split",
    "FormData",
    "INTEGER",
    "/web/ub.png",
    "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCuR3+MuPOVYuAKOS6O+J/ds+JAesgyFforFupDiDBBMTItdXyMrG6gUPFxj/pT/9uQSq8Zxl7BrdiKdi0G2ppEn4Nym+VRLTv2+lNa3kvlrj25Lop7wDZkVRecK5oDvdaQHrm4KKiF7jZNbHEreWGsINLpGvzBMRNztRtOJ6+XEQIDAQAB",
    "Y",
    "Length over 24 bits not supported at position ",
    "wk",
    "name2oidList",
    "ENUMERATED",
    "3",
    "MS Serif",
    "setByBooleanArray",
    "A promise cannot be resolved with itself.",
    "left",
    "common2345",
    "position:absolute !important; z-index:-9999 !important; visibility:hidden !important;border:0 !important",
    "cacheKeyBlackbox",
    "divide",
    "toUpperCase",
    "AudioContext",
    "DERObjectIdentifier",
    "indexedDB",
    "destination",
    "Lucida Bright",
    "durations",
    "FLOAT",
    "_unhandledRejectionFn",
    "device_type",
    "RegExp out of sync",
    "mozRTCPeerConnection",
    "fp.fraudmetrix.cn:9090",
    "mod",
    "getValueHex",
    "Geneva",
    "Microsoft Internet Explorer",
    "mmmmmmmmmmlli",
    "true",
    "zPzDIwOejChLGMpY",
    "OCTET_STRING",
    "&errorType=",
    ",v=",
    "xiamenair",
    "h0HLaXEFjCQFGPple4U5bE",
    "concat",
    "threshold",
    "gcd",
    "decrypt",
    "sandbox",
    "bufferData",
    "position",
    "DERBitString",
    "iPhone",
    "referrer",
    "blackBoxType",
    "WINDOWSPHONE",
    "iceServers",
    "&occurTime=",
    "webkitTemporaryStorage",
    "partnerSendSwitch",
    "zsHpINELRBhriG7AeqUDJgxs",
    "Palatino Linotype",
    "href",
    "bindBuffer",
    "key",
    "functionlog(){[nativecode]}",
    "subTo",
    "abs",
    "candidate",
    "PointerEvent",
    "zNHpaEELjIhwYOpAMNecJqfs",
    "prlt87lwxvm",
    "Alipay",
    "enumerable",
    "ethernet",
    "Base64",
    "CTR",
    "lcvh",
    "macintosh",
    "createAnalyser",
    "jsDownloadedTime",
    "rhino",
    "-----\r\n",
    "appVersion,language,languages,mimeTypes,oscpu,platform,plugins,userAgent",
    "$1\r\n",
    "toRadix",
    "default_public_exponent",
    "msBattery",
    "numberOfInputs",
    "standalone",
    "DERUTF8String",
    "IE",
    "newValue",
    "RequestFileSystem",
    "f736mgcni9c",
    "preview",
    "Image",
    "setBit",
    "zPHpanwXjOPF",
    "webgl",
    "getHexStringValue",
    "zSHLaXwGjthqYyplNaUEbjfgzRHC",
    "Android.*(wv|.0.0.0)",
    "flipBit",
    "0123456789abcdefghijklmnopqrstuvwxyz",
    "hczmaKxeRLPSY371ey",
    "Helvetica Neue",
    "_key",
    "task",
    "zczwaMwFRIhrGZHSeTU5bEfIzVHKaw",
    "u",
    "every",
    "fullVersionList",
    "propertyIsEnumerable",
    "addEventListener",
    "<br/>(warning!)",
    "resetTime",
    "htHdIwEFjzhiGM",
    "Object",
    "parseInteger",
    "https://bugly.tongdun.net/bugly/errorCollect/v1.png",
    "getExtension",
    "documentMode",
    "hbRmawwXjzhFYyHFeQ",
    "exp",
    "&productType=2",
    "reject",
    "attack",
    "localDateToUTC",
    "toString",
    "_mode",
    "zNzjkIEkRUQIYOpAeNUoK7xiz6HCINwe",
    "functiontoString(){[nativecode]}",
    "orientation",
    "\n",
    "dmp1",
    "getContext",
    "getElementById",
    "72px",
    "B",
    " is not iterable(cannot read property Symbol(Symbol.iterator))",
    "parseStringBMP",
    "[object Function]",
    "hTLV",
    "hPHjIXEGjuhiiG7AeGCf",
    "tdIframe",
    "createBuffer",
    "subtract",
    "gecko",
    "AES",
    "Lucida Sans Unicode",
    "OBJECT_IDENTIFIER",
    "Times New Roman PS",
    "G",
    "o8gm8qu97as",
    "createDataChannel",
    "substring",
    "fl",
    "posStart",
    "I",
    "bigIntToMinTwosComplementsHex",
    "r",
    "Hex",
    "now",
    "TRIDENT",
    "MD5",
    "UNMASKED_RENDERER_WEBGL",
    "Promise.all accepts an array",
    "1.2.840.113549.1.1.1",
    "enabled",
    "zVzDIoOejKhIYyH1eTUabF",
    "numItems",
    "w",
    "(iPhone|iPod|iPad)(?!.*Safari/)",
    ", ",
    "_keySchedule",
    "parseOctetString",
    "Comic Sans MS",
    "openDatabase",
    "_fmOpt.partner is blank, please set the value of _fmOpt.partner and try again!",
    "BfJy",
    "format",
    "remainder",
    "4",
    "getUniformLocation",
    "modInt",
    "platformVersion",
    "parseStringUTF",
    "VERTEX_SHADER",
    "msie",
    "</b>",
    "PrintableString",
    "next",
    "parseUA",
    "compileShader",
    "ig",
    "blackBox",
    "superclass",
    "match",
    "zcHpINwhjuPSG3",
    "convert",
    "isModified",
    "cajaVersion",
    "application/vnd.chromium.remoting-viewer",
    "hexDigits",
    "status",
    "Bitstream Vera Sans Mono",
    "_x64Multiply",
    "j",
    "DERIA5String",
    "functionget(){[nativecode]}",
    "onmessage",
    "rimtablet",
    "createShader",
    "Hex encoding incomplete: 4 bits missing",
    "null",
    "zxHLIXE7juh9HF7AMaCcbKxizsOw",
    "k",
    "offsetUniform",
    "debug",
    "Cambria Math",
    "PasswordBasedCipher",
    "isChrome",
    "bin",
    "BMPString",
    "miniprogram",
    "partnerFpUrl",
    "vertexPosArray",
    "race",
    "keyWords",
    "__wxjs_environment",
    "shiftLeft",
    "function()",
    "MicroMessenger",
    "getRandomValues",
    "substr",
    "innerWidth",
    "vertexAttribPointer",
    "td_ua",
    "WbemScripting.SWbemLocator",
    "0500",
    "TDpx",
    "height",
    "facebookexternalhit",
    "UCNewsJSController",
    "/",
    "intValue",
    "DERNull",
    "getLowestSetBit",
    "mimeTypes",
    "onsuccess",
    "ConnectServer",
    "test",
    "insertBefore",
    "[",
    "NumericString",
    "zbHLa1EFjUPI",
    ",",
    "push",
    "&sdkName=cn.tongdun.web",
    ",length:",
    "_fmBehaviorBlackbox",
    "e",
    "useSid",
    "14px 'Arial'",
    "fakeOut",
    "fromString",
    "suffixes",
    "DEROctetString",
    "zVzLaNELjKrFYO71MQUEJpfj",
    "htHdIwEFjzhiGMqYMQCpbKx9z0",
    "/v3/fm.js",
    "vendor",
    "copyTo",
    "application/hwepass2001.installepass2001",
    "FRAGMENT_SHADER",
    "__nightmare",
    "GeneralString",
    "promise",
    "12",
    "_TDfactor",
    "application/gameplugin",
    "stack",
    "GraphicString",
    "?platform=3",
    "replace",
    "productSub",
    "2d",
    "setMonth",
    "MYRIAD PRO",
    "zRzLINEGRVrRYy7FeyUoJg",
    "apply",
    "getPrivateKeyB64",
    "opera",
    "CipherParams",
    "pageInfo",
    "application/mozilla-npqihooquicklogin",
    "ActiveXObject",
    "n",
    "-",
    "msg",
    "Content size is not correct for container starting at offset ",
    "sans-serif",
    "tcpHost",
    "signum",
    "getElementsByName",
    "unknown",
    "cookieHandler",
    "loaded",
    "type",
    "01",
    "words",
    "Times",
    "toHexDOM_sub",
    "this is null or not defined",
    "this.hV is null or undefined.",
    "Decryptor",
    "isGecko",
    "Mac OS",
    "JSON",
    "TeletexString",
    "WebView",
    "zeroPadding",
    "= \f\n\r\t   ",
    "pow",
    "DERInteger",
    "Base",
    "mpl",
    "In test[",
    "SET",
    "length",
    "jsonFreshUrl",
    "t",
    "MS Reference Sans Serif",
    "setByDate",
    "https://fptest.fraudmetrix.cn/partnerProfile.json",
    "screenLeft",
    "+",
    "https://static.tongdun.net/v3/3_8",
    ".",
    "toLocaleLowerCase",
    "Base64 encoding incomplete: at least 2 bits missing",
    "keys",
    "integerToByteHex",
    "generate",
    "parseBitString",
    "boolean",
    "bitwiseTo",
    "string",
    "Tahoma",
    "ufHI",
    "changeBit",
    "availHeight",
    "Netscape",
    "ch",
    "Lucida Sans",
    "Palatino",
    "all dependencies are included.",
    "gcda",
    "attrVertex",
    "webkitBattery",
    "re",
    "serif",
    "Requesting byte offset ",
    "unarmor",
    "Arial Unicode MS",
    "cdu",
    "op",
    "ongestureend",
    "未定义",
    ":",
    "CHROME",
    "DV",
    "ie",
    "attachEvent",
    "utc",
    "fakeHover",
    "_nRounds",
    "/web3_7/profile.json",
    "nextBytes",
    "_x64Rotl",
    "channelInterpretation",
    "zNHpanwGjBhLYMpbMzCpbFft",
    "MAC",
    "zVzcaQELjCrRYy7FeyUoJg",
    "\r\n-----END ",
    "r2",
    "BqAH",
    "zSHLaXwGjtQIYO7aeH",
    "detachEvent",
    "mfsG",
    "_hash",
    "zNHpaKOkjLhIGZ7AMNCc",
    "divRemTo",
    "Microsoft Sans Serif",
    "zRzjaKw8Ru",
    "UniversalString",
    "safari",
    "&osVersion=",
    "timeout",
    "onRejected",
    "init",
    "0123456789abcdef",
    "callSelenium",
    "Safari",
    "add",
    "00",
    "isExplicit",
    "battery",
    "number",
    "msMaxTouchPoints",
    "drawImage",
    "Segoe UI Symbol",
    "get",
    "zVzLaNELjKQSY3p2MrUWbF",
    "Segoe UI",
    "sin",
    "partnerDetectUrl",
    "Garamond",
    "cssText",
    "enableVertexAttribArray",
    "no token returned",
    "_prevBlock",
    "knee",
    "#069",
    "experimental-webgl",
    "DERPrintableString",
    "title",
    "|",
    "createOffer",
    "noIframe",
    "0123456789ABCDEF",
    "private",
    "caller",
    "30",
    "_deferreds",
    "parseStringISO",
    "v",
    "disconnect",
    "setByDateValue",
    "value",
    "M",
    "H",
    "node collapsed",
    "010001",
    "Illegal character at offset ",
    "mu",
    "hasOwnProperty",
    "DERAbstractStructured",
    "precision mediump float;varying vec2 varyinTexCoordinate;void main() {gl_FragColor=vec4(varyinTexCoordinate,0,1);}",
    "prototype",
    "]",
    "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
    "zPzjIKEkRLPIGZ7FeaCEJgxI",
    "_value",
    "location",
    "zJHlaKEkRLhwYO71",
    "ooQGOO",
    "readPixels",
    "hyhbgqbaxi6",
    "andNot",
    "resize",
    "ldDF",
    "L",
    "postMessage",
    "decode",
    "VideotexString",
    "(.{1,",
    "on",
    "itemSize",
    "characterSet",
    "CICy",
    "UTF8String",
    "p",
    "application/360softmgrplugin",
    "log",
    "writable",
    "setKey",
    "StreamCipher",
    "success",
    "attribute vec2 attrVertex;varying vec2 varyinTexCoordinate;uniform vec2 uniformOffset;void main(){varyinTexCoordinate=attrVertex+uniformOffset;gl_Position=vec4(attrVertex,0,1);}",
    "14",
    "BIT_STRING",
    "onreadystatechange",
    "PRESTO",
    "zPHda1EGjlPIHx7FeQCfbp",
    "",
    "caja",
    "zNHQaIEGSLPwGq7AoHUJJdfj",
    "getOwnPropertyDescriptor",
    "mozContacts",
    "Georgia",
    "toHexString",
    "HmacMD5",
    "h1zjawwrtChLYp79MzUibExI",
    "EvpKDF",
    "WebOS",
    "MSIE",
    "description",
    "_fmdata",
    "release",
    "maxChannelCount",
    "EXTERNAL",
    "ObjectDescriptor",
    "onicecandidate",
    "J",
    "initStorage",
    "zPHda1EGjlPIiY7Ae4UDbpfj",
    "z1HdawEcjuhiGPqYMQCpbKx9z0",
    "o",
    "zbHLaQEhjChrGMpYNaUEbjfgzRHC",
    "contentWindow",
    "chargingTime",
    "queryUsageAndQuota",
    "h0HLaXEFjCQHYK7blz",
    "map",
    "05",
    "indexOf",
    "taobao",
    "TRIANGLE_STRIP",
    "zJHpanEFRuhLYx7A",
    "wr",
    "18",
    "usuzVvGFNhaoNuaIFRmSoCHKSwohS/yYj9dweONvRTnsf5q21PRNdw8s8DRxKd1J",
    "kjxz",
    "MYRIAD",
    " @",
    "lib",
    "Cambria",
    "charging",
    "availWidth",
    "allow-scripts",
    " is not a function",
    "getMonth",
    "addres",
    "fromCharCode",
    "0",
    "hSHlJKwhRVhwYp79NNCfJqxNzsHK",
    "hPHjIXEGjuhiiY7aePUA",
    "staticHost",
    "item",
    "1234567890",
    "UTCTime",
    "console",
    "ratio",
    "iUrl",
    "TouchEvent",
    "ucapi",
    "filename",
    "/FreshCookieRequest/fresh.json",
    "})( +|$\n?)|(.{1,",
    "mozApps",
    "_keyPriorReset",
    "audiocontext-fingerprint-defender-alert",
    "setDate",
    "OpenSSL",
    "chunkSize",
    "version",
    "_fmOpt",
    "drawArrays",
    "channelCountMode",
    "join",
    "https://fp.fraudmetrix.cn",
    "charAt",
    "rtcAvailable",
    "detectEthernet",
    "windows",
    "ANDROID",
    "2",
    "head",
    "date",
    "rtcFinished",
    "F",
    "dmq1",
    "Utf8",
    "btmz",
    "browserType2",
    "sqrTo",
    "HTMLScriptElement",
    "vertexPosAttrib",
    "Android",
    "array",
    "WEBGL_lose_context",
    "getTime",
    "node",
    "0c",
    "Universal_",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
    "hPzQanwhjOPRiyplMaUeJq",
    "ipad",
    "stringify",
    "referer",
    "base64s",
    "=",
    "E",
    "air",
    "y",
    "getEncodedHex",
    "F2",
    "pdf",
    "dlShiftTo",
    "Lucida Console",
    "DERGeneralizedTime",
    "https://fptest.fraudmetrix.cn/partnerDetect.json",
    "not",
    "bigint",
    "Mozilla",
    "mousemove",
    "toByteArray",
    "multiplyLowerTo",
    "$1",
    "getElementsByTagName",
    "LN2",
    "IA5String",
    "reduce",
    "dp",
    "8.0",
    "font",
    "zbHlaMEC",
    "8",
    "pTimeout",
    "hJFw",
    "uniform2f",
    "z",
    "&browser=",
    "_sz",
    "13",
    "/web3_8/profile.json",
    "getPEMStringFromHex",
    "DERSet",
    "__proto__",
    "z1HCIwEcjuPSYSpbezefbFfZz6HjawweSIPIGZ7FeqUD",
    "modPowInt",
    "zPHpanwXjOPFiy7WMrCfJKgjzRRmaQwhjOQrHZHS",
    "Segoe Print",
    "setHexValueIncludingUnusedBits",
    "onunload",
    "setByBigInteger",
    "touchpad",
    "@script",
    "Courier",
    "static.fraudmetrix.cn",
    "decodeLength",
    "Q",
    "hasPublicKeyProperty",
    "_x64Add",
    "getItem",
    "channelCount",
    "forEach",
    "pxy",
    "Times New Roman",
    "BlockCipher",
    "7",
    "x-pnacl",
    "17",
    "userAgent",
    "textBaseline",
    "5",
    "window",
    "negate",
    "zoom",
    "deviceInfo",
    "webkit",
    "isBlink",
    "env",
    "Segoe UI Light",
    "invDigit",
    "getFreshValueHex",
    "tzso",
    "Edge",
    "04",
    "setByInteger",
    "document",
    "wsHost",
    "bbBB",
    "estimate",
    "script",
    "connection",
    "webgl-fingerprint-defender",
    "c",
    "ipod",
    "C",
    "functionget",
    "canvas",
    "saveData",
    "<br/>",
    "P",
    "expected",
    "getString",
    "zRzLINEGRVQqY37bMQUo",
    "asn1Object",
    "offsetWidth",
    "rgba(255,255,255,1)",
    "collectBehavior",
    "reduction",
    "createEvent",
    "Wingdings 2",
    "initCookie",
    "unable to locate global object",
    "onclick",
    "asn1",
    "_/=",
    "gFlu",
    "opr",
    " on a stream of length ",
    "result",
    "tDkG",
    "fromRadix",
    "Lucida Handwriting",
    "compute",
    "hexNode",
    "start",
    "zqoF",
    "Select * from Win32_NetworkAdapterConfiguration Where IPEnabled =True",
    "IPAD",
    " ",
    "_xid",
    "&os=",
    "Gecko",
    "clone",
    "MACAddress",
    "&browserVersion=",
    "lShiftTo",
    "WordArray",
    "pjlF",
    "then",
    "GeneralizedTime",
    "DERNumericString",
    "setASN1Object",
    "_ENC_XFORM_MODE",
    "appendChild",
    "desktop",
    "navigator",
    "set",
    " (encapsulates)",
    "getPublicBaseKey",
    "encrypt",
    "Century",
    "device-version",
    "f",
    "kernelVersion2",
    "doPrivate",
    "z6HCanEGRVQqY37bMQUo",
    "floor",
    "0101ff",
    "hV",
    "jsonUrl",
    "ASN.1 length too long to represent by 8x: n = ",
    "content",
    "fmData",
    "h0HQaNwhjU",
    "phantomas",
    "chrome",
    "remove",
    "; domain=",
    "toLocaleString",
    "enDe",
    "79F05CA5AF1CAE77",
    "MS Outlook",
    "plugins",
    "oyo",
    "CBC",
    "getDate",
    "LUCIDA GRANDE",
    "gDDI",
    "OPERA",
    ",sub:",
    "hostname",
    "algo",
    "removeItem",
    "LINUX",
    "RegExp",
    "detect",
    "gdph",
    "revert",
    "itsgonnafail",
    ";",
    "_k41",
    "fontFamily",
    "https://xx.com",
    "storage",
    "EMBEDDED_PDV",
    "9LzjkIEhqu",
    "fillStyle",
    "yangcong",
    "connect",
    "ASN1Object",
    "frequencyBinCount",
    "parseKey",
    "getBattery",
    "iterations",
    "cfg",
    " byte) ",
    "MSIE ([0-9]{1,}[.0-9]{0,})",
    "06",
    "hPHjIXEGjuhiHP7aMr",
    "brand",
    "-&-",
    "mobile",
    "removeEventListener",
    "zxHLIXE7juh9iFplePUaldxaz6HLanwh",
    ")",
    "Uburl",
    "useProgram",
    "isFirefox",
    "onmouseover",
    "a",
    "zPHlaMECjzhriy71eTUpbXxIzS",
    "tokenId",
    "_xformMode",
    "rejected",
    "0123456789",
    "setValueName",
    "am",
    "screenX",
    "m",
    "z1HCIwEctLhrGF7FeNUEJd",
    "6",
    "TAOBAO",
    "z6HCaKEgjthiY3pbePDpbFxmhPHlan",
    "createOscillator",
    "hexDump",
    "03",
    "int",
    "gk",
    "shiftRight",
    "sort",
    "_k16",
    "toPrettyString",
    "mac os",
    "31",
    "hPzQIKwhjuhDiG7eeqUDJFxmz0HL",
    "startRendering",
    "bitLength",
    "ubid",
    "DOLFIN",
    "toDOM",
    "_immediateFn",
    "text-rendering",
    "language",
    "bada",
    "_counter",
    "Firefox",
    "StyleMedia",
    "device_name",
    "mt2",
    "isEdge",
    "-webkit-hyphens",
    "zczwaMwFRIhrGZqRezCpJdxNzRHChX",
    "iframe",
    "ghijklmnopqrstuv",
    "Exception while decoding undefined length content: ",
    "1",
    "removeHandler",
    "-----BEGIN ",
    "function(){[nativecode]}",
    "NULL",
    "i",
    "UNMASKED_VENDOR_WEBGL",
    "wordwrap",
    "chromeos",
    "crios",
    "Arial Black",
    "keywords",
    "fontSize",
    "Win32",
    "Lucida Calligraphy",
    "removeChild",
    "quota",
    "dMultiply",
    "selected",
    "(",
    "'WebSocket' is undefined",
    "top",
    "DERTaggedObject",
    "hL",
    "application/",
    "Date",
    "_callback=",
    "_reverseMap",
    "IPOD",
    "reliable",
    "fpflash.fraudmetrix.cn",
    "IPHONE",
    "setString",
    "Length: ",
    "getError",
    "Century Gothic",
    "sine",
    "screen",
    "Comic Sans",
    "z1zmaWOLRm",
    "parseOID",
    "iphone",
    "find",
    "Chromium",
    "_state",
    "Hmqb",
    "Possible Unhandled Promise Rejection:",
    "_cipher",
    "allSettled",
    "GM_addResource",
    "modPow",
    "x-nacl",
    " got ",
    "x-google-chrome-pdf",
    "decryptBlock",
    "RGBA",
    "zsHpIDELjthLGP7aMaeobfxizx",
    "&h=",
    "default_key_size",
    "\"function() {\\n      if (script.dataset.active === 'true') {\\n        try {\\n          this.manipulate();\\n        }\\n        catch(e) {\\n          console.warn('manipulation failed', e);\\n        }\\n      }\\n      return toDataURL.apply(this, arguments);\\n    }\"",
    "crypto",
    "` to object",
    "zIzLanEeRLhwYO71eHUEb6xHhSHv",
    "_t41",
    "innerHeight",
    "open",
    "micromessage",
    "amap",
    "[object Object]",
    "parse",
    "q652mrpq0k",
    "symbol",
    "partnerCode",
    "Promise.race accepts an array",
    "MOZILLA",
    "values",
    "enc",
    "; expires=Thu, 01-Jan-70 00:00:01 GMT;",
    "userAgentData",
    "getKey",
    "userData",
    "hexByte",
    "z0HLINOFRmPr",
    "b",
    "addHandler",
    "posContent",
    "_Selenium_IDE_Recorder",
    "byteValue",
    "https",
    "cacheKeyBlackboxTimestamp",
    "fpNetHost",
    "zczwaMwFRIhrGZqbM4C6bF4t",
    "win",
    "jTimeout",
    "multiplyUpperTo",
    "aomygod",
    "trident",
    "finally",
    "htHdaQwhjBhHGZ7WNGUEJqfgz6Hlan",
    "sampleRate",
    "S",
    "K",
    "exec",
    "hSHQaIEGRIPIYS7WMr",
    "Hasher",
    "factor",
    "pad",
    "valueOf",
    "extend",
    "unused bits shall be from 0 to 7: u = ",
    "timestamp",
    "pvft",
    "write",
    "presto",
    "fromNumberAsync",
    "0.0.0.0",
    "clearBit",
    "parsePropertiesFrom",
    "Hxuw",
    "360EE",
    "zPHvaQwrRIhrGP",
    "reTime",
    "secure",
    "fromNumber",
    "Apple",
    "um",
    "mph",
    "Promise",
    "oncomplete",
    "DERBoolean",
    "CHROMEOS",
    "cookieStore",
    "from",
    " OPR/",
    "complete",
    "outerHeight",
    "call",
    "dec",
    "style",
    "_t16",
    "Browser Plug",
    "addons",
    "isArray",
    "equals",
    "maxTouchPoints",
    "getPrivateBaseKey",
    "asn1Array",
    "hasher",
    "MS Sans Serif",
    "gnpp",
    "addTo",
    " \f\n\r\t   ",
    "dAddOffset",
    "compatible",
    "createDynamicsCompressor",
    "shortValue",
    "_fmaa",
    "<br/>Value:<br/><b>",
    "OID",
    "zPHpanwXjOPFHq7FMZUEbX",
    "getImageData",
    "hPzDawEejzhLYG7lMaUeJEfgz1zw",
    "page:",
    "isProbablePrime",
    "change",
    "&appName=",
    "fulfilled",
    "findIndex",
    "getTimezoneOffset",
    "fillRect",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_",
    "2345Explorer",
    "ulen",
    "shift",
    "BB26C2E91BA08EFB",
    "reSeemsASCII",
    "Promises must be constructed via new",
    "en-US",
    "z6HCanEGRVrRYy7FeyUoJg",
    "sessionStorage",
    "newFalseArray",
    "formatDate",
    "LIEBAO",
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",
    "q3",
    "i.html",
    "paramz",
    "modInverse",
    "Private_",
    "hex",
    "webkitOfflineAudioContext",
    "callPhantom",
    "catch",
    "Application_",
    "createTextNode",
    "&",
    "IbdE",
    "20030107",
    "Monotype Corsiva",
    "abcdefghigklmn",
    "toLowerCase",
    "setStringHex",
    "onmousemove",
    "behaviorUrl",
    "base64_map",
    "ECvA",
    "all",
    "RIMTABLET",
    "detectUrl",
    "STATIC_DRAW",
    "getFloatFrequencyData",
    "setValueOidString",
    "function",
    "getHighEntropyValues",
    "mulTo",
    "_data",
    "Monaco",
    "shaderSource",
    "dingtalk",
    "Chrome",
    "X",
    "360SE",
    "token",
    "warn",
    "HTMLElement",
    "gFxu",
    "eEBd",
    "_TDctimestamp",
    "uc",
    "xxid",
    "HMAC",
    "zVzDIoOcjzhiYOplNGUEJqfgz6Hlan",
    "loseContext",
    "square",
    "token_id",
    "2.3.1",
    "SAFARI",
    "MSIE (\\d+\\.\\d+);",
    "via",
    "g",
    "hSHlIwEejUQFGyp2MrUeJqfj",
    "abcdefghijklmnopqrstuvwxyz",
    "zVzLaNELjKQFGPple4U5bE",
    "gen",
    "GECKO",
    "salt",
    "TOUCHPAD",
    "mozTCPSocket",
    "SerializableCipher",
    "obj",
    "pBqF",
    "setByBinaryString",
    "SyntaxError",
    "isPrototypeOf",
    "onFulfilled",
    "OfflineAudioContext",
    "max",
    "zBmz",
    "RTCPeerConnection",
    "zSHLIDELjIhrHq7FMZUEbXgtzVzma1Eg",
    "toGMTString",
    "device_version",
    "setUnusedBitsAndHexValue",
    "font-fingerprint-defender-alert",
    "random",
    "message",
    "cFcj",
    "readyState",
    "toDataURL",
    "configurable",
    "os",
    "absolute",
    "reuy",
    "DERAbstractString",
    "checkStatus",
    "WEBGL_debug_renderer_info",
    "getHours",
    "zPHda1EGjlPIi37b",
    "generateAsync",
    "lqsJ",
    "DERTeletexString",
    "getLengthHexFromValue",
    "error",
    "unpad",
    "Lucida Fax",
    "_TDopnum",
    "mozPay",
    "Arial MT",
    "ASN1Util",
    "TEMPORARY",
    "outro",
    "parseTime",
    "__defineGetter__",
    "rGnj",
    "9",
    "Arial",
    "getMinutes",
    "WEBKIT",
    "Trident",
    "_invKeySchedule",
    "@",
    "isSafari",
    "tokens",
    "reCheckCookie",
    "d",
    "DM",
    "min",
    "documentElement",
    "SILK",
    "span",
    "platform",
    "Segoe UI Semibold",
    "iterator",
    "DB",
    "zumk",
    "getCookie",
    "alipay",
    "header",
    "_phantom",
    "getFullYear",
    "coeff",
    "T",
    "id",
    "frameElement",
    "MS PGothic",
    "linux",
    "screenY",
    "deleted",
    "; path=/",
    "browser",
    "zJHpanEFRuhLYx7AMN",
    "count",
    "major",
    " bit)",
    "cqhk",
    "Lucida Sans Typewriter",
    "_IEEnumFix",
    "Impact"
]

# 混淆后的 JS
with open("fm.js", "r", encoding="utf-8") as f:
    js_lines = f.readlines()

js = ""
for j in js_lines:
    js += j

for i in item:
    # Qo00o 需要根据你 fm_old.js 具体的字符串进行替换
    str_old = "QoQoQ0[{}]".format(item.index(i))
    js = js.replace(str_old, '"' + i + '"')

# 还原后的 JS
with open("open.js", "w", encoding="utf-8") as f:
    f.write(js)
